# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4.3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  price-store:
    image: price-store
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_URL: mongodb://root:example@mongo:27017/db?connect=direct&authSource=admin&authMechanism=SCRAM-SHA-256
#      DB_URL: postgresql://postgres:password@db:5432/postgres?sslmode=disable