POST http://localhost:4000/processCSV?url=http://localhost:3000/exampleCSV1

###

POST http://localhost:4000/processCSV?url=http://localhost:3000/exampleCSV2

###

GET http://localhost:4000/listProducts?limit=1&order=name DESC
Accept: application/json

###
